global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'django'
    static_configs:
      - targets: ['backend:8000']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
